import TheHeader from '@/components/TheHeader';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import TheFooter from '@/components/TheFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
    icons: {
        icon: [
            {
                url: '/favicon/favicon-16x16.png',
                sizes: '16x16',
                type: 'image/png',
            },
            {
                url: '/favicon/favicon-32x32.png',
                sizes: '32x32',
                type: 'image/png',
            },
            { url: '/favicon/favicon.ico', sizes: 'any' },
        ],
        apple: [
            {
                url: '/favicon/apple-touch-icon.png',
                sizes: '180x180',
                type: 'image/png',
            },
        ],
        other: [
            {
                rel: 'manifest',
                url: '/favicon/site.webmanifest',
            },
        ],
    },
    manifest: '/favicon/site.webmanifest',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TheHeader />
                <main className="container">{children}</main>
                <TheFooter />
            </body>
        </html>
    );
}
